### ISSUE TITLE
Is it legit?

### ISSUE THREAD

**Issue by 1cloud11** [ValvePython/csgo#34]
Hi! Im not sure, but want to know your opinion, is it legit to use this? Have you done any researches about valve rules?

**Comment by tmick0** [comment]
I am not a lawyer not a representative of this project, but the following is present in the Steam subscriber agreement:

> You are entitled to use the Content and Services for your own personal use, but **you are not entitled to:** (i) sell, grant a security interest in or transfer reproductions of the Content and Services to other parties in any way, nor to rent, lease or license the Content and Services to others without the prior written consent of Valve, except to the extent expressly permitted elsewhere in this Agreement (including any Subscription Terms or Rules of Use); (ii) host or provide matchmaking services for the Content and Services or **emulate or redirect the communication protocols used by Valve in any network feature of the Content and Services, through protocol emulation, tunneling, modifying or adding components to the Content and Services, use of a utility program or any other techniques now known or hereafter developed, for any purpose including, but not limited to network play over the Internet, network play utilizing commercial or non-commercial gaming networks or as part of content aggregation networks, websites or services, without the prior written consent of Valve**; or (iii) exploit the Content and Services or any of its parts for any commercial purpose, except as expressly permitted elsewhere in this Agreement (including any Subscription Terms or Rules of Use).

(emphasis mine)

Pretty sure use of this library counts as "emulation of the communication protocols used by Valve" so therefore violates the agreement. I wouldn't expect valve to shut you down over small volumes of traffic, however I would at least take the precaution of using a dedicated bot account with this library as to not get your main account TOS'd.

**Comment by rossengeorgiev** [comment]
This package, steamkit, and various other implementations have existed for many years. It's almost certain that one is used in any site related to Steam, Dota 2, CSGO, TF2. Without them those sites are not possible. Ultimately, these libraries are implementations of Steam's protocol and are limited by it. 

Would your account get banned if you used them? The short answer is no. Now if you are doing some really stupid, or spamming, the answer is maybe. To illustrate this point, read on the skins gambling sites. Eventually their shenanigans forced Valve to step in.

In general, Valve very rarely full bans accounts, probably because it erodes Steam's ecosystem. For bad actors, there are game bans, trade bans, community bans, etc. There is no need to read the TOS to know whether they can terminate your account. It's a service, not a right.

**Comment by 1cloud11** [comment]
Thank you very much!
